#!/bin/bash

cd $OPENSHIFT_DATA_DIR

if [ ! -d "$OPENSHIFT_DATA_DIR/jdk1.8.0_05" ]; then
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    tar -zxf jdk-8u5-linux-x64.tar.gz
fi


cd $OPENSHIFT_REPO_DIR

export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"
export DROPWIZARD_PASSPHRASE='i am going to see some sunshine'

if [ "$OPENSHIFT_APP_NAME" = "gasguzzler" ]
then
    export MYBRANCH="master"
else
    export MYBRANCH="dev"
fi

git ls-remote https://github.com/spinetrak/gasguzzler.git -h $MYBRANCH

export MYBUILD=`git ls-remote https://github.com/spinetrak/gasguzzler.git -h master | awk '{ print $1 }'`

$OPENSHIFT_REPO_DIR/mymvn -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -q -DskipTests=true -Dbuild.branch=$MYBRANCH -Dbuild.number=$MYBUILD package



