#!/bin/bash
cd $OPENSHIFT_REPO_DIR

if [ "$OPENSHIFT_APP_NAME" = "gasguzzler" ]
then
    cp config/config-rhc.yml config.yml
else
    cp config/config-rhc-dev.yml config.yml
fi


sed -i 's/@OPENSHIFT_DIY_IP@/'"$OPENSHIFT_DIY_IP"'/g' config.yml
sed -i 's/@OPENSHIFT_DIY_PORT@/'"$OPENSHIFT_DIY_PORT"'/g' config.yml
sed -i 's/@SOME_OTHER_PORT@/'"$OPENSHIFT_DIY_PORT"'/g' config.yml
sed -i 's/@OPENSHIFT_POSTGRESQL_DB_HOST@/'"$OPENSHIFT_POSTGRESQL_DB_HOST"'/g' config.yml
sed -i 's/@OPENSHIFT_POSTGRESQL_DB_PORT@/'"$OPENSHIFT_POSTGRESQL_DB_PORT"'/g' config.yml
