#!/bin/bash
cd $OPENSHIFT_REPO_DIR
cp config/config-rhc.yml config.yml
sed -i 's/@OPENSHIFT_DIY_IP@/'"$OPENSHIFT_DIY_IP"'/g' config.yml
sed -i 's/@OPENSHIFT_DIY_PORT@/'"$OPENSHIFT_DIY_PORT"'/g' config.yml
sed -i 's/@SOME_OTHER_PORT@/'"$OPENSHIFT_DIY_PORT"'/g' config.yml
