env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "z7SxlBk1jD1y+7USJLtAxBrpAzz1/noZf2JwadAte83/Q8ru0ajpJlQjNcEsBDyAPs0s6VVHpvATP5/Uix1t8SMDAIQj2bzq+/P6t58vN+oD1V9SQOhIuh+iPHvzMWIyK01SCytOnNX1ggqS/CQyFr7eaFxdobZvt1/TiYBWfLQ="

language: java

script: mvn test

services: postgresql

addons:
  coverity_scan:
    project:
      name: "spinetrak/gasguzzler"
      description: "Build submitted via Travis CI"
    notification_email: renzop@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database gasguzzlerdb;' -U postgres
  - psql -f ./setup_postgres.sql
  
after_success:
  - mvn clean cobertura:cobertura coveralls:report