server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: server.jks
      keyStorePassword: spinetrak
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: server.jks
      keyStorePassword: spinetrak
      validateCerts: false


database:
  driverClass: org.postgresql.Driver
  user: gasguzzler
  password: gasguzzler
  url: jdbc:postgresql://localhost/gasguzzlerdb

