server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    bindHost: @OPENSHIFT_DIY_IP@
    port: @OPENSHIFT_DIY_PORT@
isHttps: true
emailService:
  from: "The Gasguzzler <mailgun@mg.spinetrak.net>"
  root: "https://gasguzzlerdev-spinetrak.rhcloud.com"
  endpoint: "https://api.mailgun.net/v2/mg.spinetrak.net/messages"
  key:
    salt: "rbvrnQ=="
    iv: "3Z1JoQHNkOLaAnMMTAY+xg=="
    value: "UD+fUM/qpgK5P25q9vuffwJOtI8eObTZ9wdJWgDNt1DNFQW+xzcaQUs/eIctuEtJ"
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
admin:
  email: "spinetrak@spinetrak.net"
  username:
    salt: "67XFnA=="
    iv: "uWiHOq7etiJPft7SHPHNrQ=="
    value: "PMPXa86M0G7PBSeUTRFOzA=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
  password:
    salt: "hA0mjQ=="
    iv: "x+fbSq9p5Fp1lpE79oSp/g=="
    value: "H6z1+AzBDeq6lGxX1DQrgw=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
database:
  driverClass: "org.postgresql.Driver"
  url: "jdbc:postgresql://@OPENSHIFT_POSTGRESQL_DB_HOST@:@OPENSHIFT_POSTGRESQL_DB_PORT@/gasguzzlerdev"
  user:
    salt: "jjn9zA=="
    iv: "QCU267m/vgUwWQuaZ3fgYg=="
    value: "bRaeYNCwN5E5TPCRaNNxSg=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
  password:
    salt: "2ueivw=="
    iv: "qEUj187Tsff+u71cZsq/dA=="
    value: "21NCUzj/xcJpc36ydTyUWw=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
