server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationConnectors:
   - type: http
     bindHost: @OPENSHIFT_DIY_IP@
     port: @OPENSHIFT_DIY_PORT@
  adminConnectors:
   - type: http
     bindHost: @OPENSHIFT_DIY_IP@
     port: @SOME_OTHER_PORT@
     
database:
  driverClass: "org.postgresql.Driver"
  user: "adminbfsllnl"
  url: "jdbc:@OPENSHIFT_POSTGRESQL_DB_URL@"
  password:
    salt: "yD4GWg=="
    iv: "Zl+NX3PM7iOPl2ImOSSg3A=="
    value: "qnILaV1Wh2MPyEzY5nJUeQ=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true