server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
isHttps: false
admin:
  username:
    salt: "67XFnA=="
    iv: "uWiHOq7etiJPft7SHPHNrQ=="
    value: "PMPXa86M0G7PBSeUTRFOzA=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
  password:
    salt: "hA0mjQ=="
    iv: "x+fbSq9p5Fp1lpE79oSp/g=="
    value: "H6z1+AzBDeq6lGxX1DQrgw=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
database:
  driverClass: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost/gasguzzlerdb"
  user:
    salt: "sXq2vA=="
    iv: "AxZzNcZvverkQKmw0yjqoA=="
    value: "qN98ioJiLmSCvw1LtSn9Qg=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
  password:
    salt: "jHOQAg=="
    iv: "SVrdLjvAtt9y1wqWKeGEfw=="
    value: "KGe4/12GgiMYjL/DSdsOow=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true