server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    bindHost: @OPENSHIFT_DIY_IP@
    port: @OPENSHIFT_DIY_PORT@
isHttps: true
admin:
  username:
    salt: "67XFnA=="
    iv: "uWiHOq7etiJPft7SHPHNrQ=="
    value: "PMPXa86M0G7PBSeUTRFOzA=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
  password:
    salt: "hA0mjQ=="
    iv: "x+fbSq9p5Fp1lpE79oSp/g=="
    value: "H6z1+AzBDeq6lGxX1DQrgw=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
database:
  driverClass: "org.postgresql.Driver"
  url: "jdbc:postgresql://@OPENSHIFT_POSTGRESQL_DB_HOST@:@OPENSHIFT_POSTGRESQL_DB_PORT@/gasguzzler"
  user:
    salt: "BuIDig=="
    iv: "SRWggJvTtf6kqIb27bdleQ=="
    value: "WlEKHk2a0JAD7LVA3qme3w=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
  password:
    salt: "yD4GWg=="
    iv: "Zl+NX3PM7iOPl2ImOSSg3A=="
    value: "qnILaV1Wh2MPyEzY5nJUeQ=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true