server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 9080
    - type: https
      port: 9443
      keyStorePath: server.jks
      keyStorePassword: spinetrak
      validateCerts: false
  adminConnectors:
    - type: http
      port: 9081
    - type: https
      port: 9444
      keyStorePath: server.jks
      keyStorePassword: spinetrak
      validateCerts: false

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password:
  url: jdbc:postgresql://localhost/gasguzzlerdb
