server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    bindHost: @OPENSHIFT_DIY_IP@
    port: @OPENSHIFT_DIY_PORT@
isHttps: true
database:
  driverClass: "org.postgresql.Driver"
  url: "jdbc:postgresql://@OPENSHIFT_POSTGRESQL_DB_HOST@:@OPENSHIFT_POSTGRESQL_DB_PORT@/gasguzzlerdev"
  user:
    salt: "jjn9zA=="
    iv: "QCU267m/vgUwWQuaZ3fgYg=="
    value: "bRaeYNCwN5E5TPCRaNNxSg=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
  password:
    salt: "2ueivw=="
    iv: "qEUj187Tsff+u71cZsq/dA=="
    value: "21NCUzj/xcJpc36ydTyUWw=="
    cipher: "aes-256-cbc"
    keyDerivation: "pbkdf2"
    keyLength: 256
    iterations: 2000
    encrypted: true
