ALTER TABLE st_user ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE st_user ALTER COLUMN updated SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE st_session ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP;